### PR TITLE
background color for the component tutorial. Alt for all images. Key …

### PR DESCRIPTION
**Pull request by Maxime-Thibaud**
background color for the component tutorial. Alt for all images. Key for the textarea

### CODE REVIEW

**Comment by rocambille** [comment]
there are conflicts to resolve :/

**Comment by Maxime-Thibaud** [comment]
Conflicts resolved !

**Comment by rocambille** [comment]
new ones with the last PR merged, sorry :/

**Comment by Maxime-Thibaud** [comment]
Resolved again !

**Pull request merged**
